image: "danger89/gtk3-docker-cmake-ninja"

stages:
  - test
  - build
  - publish

static_code_analysis:
  stage: test
  script: ./scripts/cpp_check.sh

build:
  stage: build
  script: ./scripts/build_prod.sh
  artifacts:
    name: "Packages + Documentation"
    expire_in: 1 week
    paths:
    - doc/doxygen/
    - build_prod/WineGUI-*.deb
    - build_prod/WineGUI-*.rpm
    - build_prod/WineGUI-*.tar.gz
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build_prod/bin
      policy: push

publish:
  stage: publish
  only:
    - tags
  except:
    - branches
  script:
    - export APP_VERSION=`./build_prod/bin/winegui --version`; $APP_VERSION
    - ./scripts/upload_release.sh
    - ./scripts/create_release_links.sh
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build_prod/bin
      policy: pull

#unit_test:
#  stage: test
#  script: ./build_prod/bin/runTests
#  cache:
#      key: "$CI_PIPELINE_ID"
#      policy: pull
#      paths:
#        - build_prod/bin/
